site_name: Eostrebis
site_url: http://eostrebis.fr
nav:
 - Home: index.md
 - Création de Personnage: Misc/Création de Personnages.md
 - Eostrebis: Eostrebis/Eostrebis.md
 - Sorts: sorts.md
 - Équipements: equipments.md
 - Classes: classes.md
 - Races: races.md
 - Créateur de Personnage: creator.md
 - Historiques: backgrounds.md
 - Dons: feats.md
 - Dons de Départ: start_feats.md
 - Dons de Prestige: prestige_feats.md
 - Objets Magiques: magic_items.md
 - Règles Maison: Misc/House_Rules.md
 - Propriétés d'Arme: Misc/Propriétés_d'arme.md

theme:
    name: 'material'
    custom_dir: 'custom-theme/'
    features:
        - search.suggest
        - navigation.top
        - navigation.path
    logo: Illustrations/repo-24.svg
    favicon: Illustrations/j20.png  

    palette:

    # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: custom
        accent: custom
        toggle:
          icon: material/weather-night
          name: Switch to dark mode

    # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: custom
        accent: custom
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode

extra_css: [loader.css, design.css]

# Extensions
markdown_extensions:
  - footnotes
  - tables
  - attr_list
  - pymdownx.arithmatex:
  #     generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  - def_list
  # - pymdownx.critic
  # - pymdownx.caret
  # - pymdownx.keys
  # - pymdownx.mark
  - pymdownx.tilde
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks-eostrebis 


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/loader.js

